// angular-12.2.15/angular-v12/src/app/music-card/music-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-music-card',
  templateUrl: './music-card.component.html',
  styleUrls: ['./music-card.component.css']
})
export class MusicCardComponent {
  @Input() name: string = '';
  @Input() favorite = false;

  constructor() { }
}

<div class="card">
  <p class="name">
    {{ name }}
  </p>
  <span *ngIf="favorite" className="fav-icon">❤️</span>
</div>

// react-16.12.0/src/music-card/MusicCard.tsx
import React from 'react';
import "./styles.css";

const MusicCard = (props: { name: string; favorite: boolean }) => {
  return (
    <div className="card">
      <p className="name">{props.name}</p>

      {props.favorite ? <span className="fav-icon">❤️</span> : null}
    </div>
  );
};

export default MusicCard;
